apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001
  selector:
    app: node-app
