apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: flask-app
          image: your-docker-repo/flask-app:latest
          env:
            - name: OPTION_A
              value: "Cats"
            - name: OPTION_B
              value: "Dogs"
            - name: REDIS_HOST
              value: "redis"
          ports:
            - containerPort: 80
